application:
  name: "spring-boot-homefinance-backend"
  description: "Home Finance Backend Spring Boot app using Scala"

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always

logging:
  file:
    name: logs/spring-boot-scala-example.log